import React from 'react';
import { Box, Typography, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Paper } from '@mui/material';
import { UserProfile, InstituteSettings } from '../types';
import { format } from 'date-fns';

interface Props {
  users: UserProfile[];
  settings: InstituteSettings | null;
  title: string;
}

const PrintableMemberDirectory = React.forwardRef<HTMLDivElement, Props>(({ users, settings, title }, ref) => {
  return (
    <Box 
      ref={ref} 
      className="a4-print-page"
      sx={{ 
        bgcolor: 'white',
        color: 'black',
        display: 'none',
        '@media print': {
          display: 'block',
        },
      }}
    >
      <Box sx={{ mb: 4, textAlign: 'center', borderBottom: '2px solid black', pb: 2 }}>
        <Typography variant="h4" sx={{ fontWeight: 900 }}>{settings?.instituteName || 'AL-ASAR INSTITUTE'}</Typography>
        <Typography variant="h6" sx={{ fontWeight: 800 }}>{title}</Typography>
        <Typography variant="caption">Generated on: {format(new Date(), 'PPPP')}</Typography>
      </Box>

      <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid black' }}>
        <Table size="small">
          <TableHead>
            <TableRow sx={{ bgcolor: '#eee' }}>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>S.No</TableCell>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>Member Name</TableCell>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>Parentage</TableCell>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>ID / Reg No</TableCell>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>Role / Class</TableCell>
              <TableCell sx={{ fontWeight: 900, border: '1px solid black' }}>Contact</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {users.map((user, index) => (
              <TableRow key={user.uid}>
                <TableCell sx={{ border: '1px solid black' }}>{index + 1}</TableCell>
                <TableCell sx={{ fontWeight: 800, border: '1px solid black' }}>{user.displayName}</TableCell>
                <TableCell sx={{ border: '1px solid black' }}>{user.fatherName || '-'}</TableCell>
                <TableCell sx={{ fontWeight: 700, border: '1px solid black' }}>{user.studentId || user.staffId || '-'}</TableCell>
                <TableCell sx={{ border: '1px solid black' }}>{user.classLevel || user.role}</TableCell>
                <TableCell sx={{ border: '1px solid black' }}>{user.phone || '-'}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      <Box sx={{ mt: 10, display: 'flex', justifyContent: 'space-between' }}>
        <Box sx={{ textAlign: 'center', width: 200 }}>
          <Box sx={{ borderTop: '1px solid black', pt: 1 }}>
            <Typography variant="caption" sx={{ fontWeight: 900 }}>Generated By</Typography>
          </Box>
        </Box>
        <Box sx={{ textAlign: 'center', width: 200 }}>
          <Box sx={{ borderTop: '1px solid black', pt: 1 }}>
            <Typography variant="caption" sx={{ fontWeight: 900 }}>Authorized Stamp</Typography>
          </Box>
        </Box>
      </Box>
    </Box>
  );
});

export default PrintableMemberDirectory;
